name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 168.231.125.167
          username: infopoint
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/infopointalbania-site
            git pull
